sudo:
language: generic
services:
 - docker

before_install:
  - docker build -t ssabin/react-test -f ./client/Dockerfile.dev ./client

script:
  - - docker run -e CI=true ssabin/react-test npm test

after_success:
  - docker built -t ssabin/multi-client ./client
  - docker built -t ssabin/multi-nginx ./nginx
  - docker built -t ssabin/multi-server ./server
  - docker built -t ssabin/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push ssabin/multi-client
  - docker push ssabin/multi-nginx
  - docker push ssabin/multi-server
  - docker push ssabin/multi-worker
